"""P03 FractalLab — simulation wiring."""
from __future__ import annotations
from pathlib import Path
from typing import Any
from PyQt6.QtWidgets import QWidget
from lumina.core.engine import Category, Effort, Level, SimulationBase
from lumina.modules.pure_maths.p03_fractallab.ui import FractalLabWidget

class FractalLab(SimulationBase):
    ID = "P03"
    NAME = "FractalLab"
    CATEGORY = Category.PURE_MATHS
    LEVEL = Level.A_LEVEL
    EFFORT = Effort.LOW
    DESCRIPTION = "Mandelbrot and Julia sets with deep zoom and colour mapping."
    TAGS = ["fractal", "Mandelbrot", "Julia", "complex", "iteration", "zoom"]
    HELP_TEXT = """# FractalLab

Explore Mandelbrot, Julia, Burning Ship, Tricorn, Multibrot, and Newton fractals.

## What it shows
Fractals are infinitely complex patterns generated by simple iterative rules in the complex plane. Each pixel is coloured by how quickly the iteration escapes (or converges).

## Fractal types
- Mandelbrot: z = z^2 + c — the classic fractal, c varies over the plane
- Julia: z = z^2 + c — c is fixed, z0 varies. Each c value gives a different Julia set
- Burning Ship: z = (|Re(z)| + i|Im(z)|)^2 + c — asymmetric, ship-like shape
- Tricorn: z = conj(z)^2 + c — three-fold symmetry
- Multibrot: z = z^N + c — generalised Mandelbrot for arbitrary power N
- Newton: Newton's method on z^3 - 1 = 0 — coloured by convergence speed

## Controls
- Fractal Type: select from the dropdown
- Julia c (Re, Im): set the c parameter for Julia sets
- Multibrot Power (N): exponent for the Multibrot set (2-12)
- max iter: maximum iterations — higher values reveal more detail but compute slower
- Compute: recompute at the current zoom level (this is the key feature!)
- Reset View: return to the default view for the current fractal type

## How to zoom
- Use the scroll wheel to zoom into a region of interest
- The image will look blocky — this is expected
- Press Compute to rerender at full resolution for the zoomed area
- Repeat to explore deeper and deeper structures

## Try this
- Zoom into the boundary of the Mandelbrot set — infinite detail at every scale
- Try Julia c = (-0.7, 0.27015) for a classic connected Julia set
- Compare Multibrot N=3, 4, 5 — notice the N-fold symmetry
- Newton's fractal has a completely different character — boundaries between convergence basins
"""

    def __init__(self) -> None:
        self._widget: FractalLabWidget | None = None

    def build_ui(self) -> QWidget:
        self._widget = FractalLabWidget()
        return self._widget

    def reset(self) -> None:
        if self._widget:
            self._widget.set_params({"type": "Mandelbrot", "max_iter": 256})
            self._widget._reset_zoom()

    def export(self, path: str) -> None:
        if not self._widget: return
        d = Path(path)
        d.mkdir(parents=True, exist_ok=True)
        self._widget._plot.export_png(d / f"{self.ID}_fractal.png")

    def get_state(self) -> dict[str, Any]:
        s = super().get_state()
        if self._widget: s["params"] = self._widget.get_params()
        return s

    def set_state(self, state: dict[str, Any]) -> None:
        if self._widget and "params" in state:
            self._widget.set_params(state["params"])
